# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N5VTrFTy3-pVgvZEDm_rR8jTeonkitJ_
"""

!git clone https://github.com/neubig/nlptutorial.git

import numpy as np
import random
import math
from tqdm.notebook import tqdm
from collections import defaultdict
import re
import nltk
from nltk.corpus import stopwords
code_regex = re.compile('[!"#$%&\'\\\\()*+,-./:;<=>?@[\\]^_`{|}~「」〔〕“”〈〉『』【】＆＊・（）＄＃＠。、？！｀＋￥％]')
nltk.download('stopwords')
stop_words = stopwords.words('english')

class IDA():
  def __init__(self, num_topics = 2):
    self.num_topics = num_topics
    self.xcorpus = []
    self.ycorpus = []
    self.xcounts = defaultdict(lambda: 0)
    self.ycounts = defaultdict(lambda: 0)
    self.vocabs = defaultdict(lambda: 0)

  def initialization(self, file_name):
    with open(file_name, encoding="utf-8") as f:
      for line in f:
        line = re.sub('&apos', '', line)
        line = re.sub('&quot', '', line)
        line = code_regex.sub('', line)
        line = re.sub(' +', ' ', line)
        docid = len(self.xcorpus)
        words = line.strip().split(" ")
        words = [word for word in words if not word in stop_words]
        topics=[]
        for word in words:
          self.vocabs[word]+=1
          topic = random.randint(0, self.num_topics-1)
          topics.append(topic)
          self.addcounts(word, topic, docid, 1)
        self.xcorpus.append(words)
        self.ycorpus.append(topics)

  def addcounts(self, word, topic, docid, amount):
    self.xcounts[topic] += amount
    self.xcounts[word+","+str(topic)] += amount
    self.ycounts[docid] += amount
    self.ycounts[str(topic)+","+str(docid)] += amount
    if (self.xcounts[topic] < 0 or self.xcounts[word+","+str(topic)] < 0 or 
        self.ycounts[docid] < 0 or self.ycounts[str(topic)+","+str(docid)] < 0):
      raise Exception('Error!')

  def sampleone(self, probs):
    z = sum(probs)
    remaining = random.uniform(0, z)
    for i in range(len(probs)):
      remaining -= probs[i]
      if remaining <= 0:
        return i

  def sampling(self, iteration, alpha, beta):
    for iter in tqdm(range(iteration)):
      ll=0
      for i in range(len(self.xcorpus)):
        for j in range(len(self.xcorpus[i])):
          x = self.xcorpus[i][j]
          y = self.ycorpus[i][j]
          self.addcounts(x, y, i, -1)
          probs = []
          for k in range(self.num_topics):
            p_xk = (self.xcounts[x+","+str(k)]+alpha)/(self.xcounts[k]+alpha*len(self.vocabs))
            p_ky = (self.ycounts[str(k)+","+str(y)]+beta)/(self.ycounts[y]+beta*self.num_topics)
            probs.append(p_xk*p_ky)
          new_y = self.sampleone(probs)
          ll += math.log(probs[new_y])
          self.addcounts(x, new_y, i, 1)
          self.ycorpus[i][j] = new_y
    answer = defaultdict(lambda: defaultdict(lambda: 0))
    for i in range(len(self.xcorpus)):
      for j in range(len(self.xcorpus[i])):
        answer[self.ycorpus[i][j]][self.xcorpus[i][j]]+=1
    for i in range(self.num_topics):
      print("topic_"+str(i))
      strings = ''
      for word, num in sorted(answer[i].items(), key=lambda x:x[1], reverse=True)[:30]:
        strings+=word+": "+str(num)+", "
      print(strings)

#テスト
train_input = "/content/nlptutorial/test/07-train.txt"
ida = IDA()
ida.initialization(train_input)
ida.sampling(10, 5, 5)

#演習問題
train_input = "/content/nlptutorial/data/wiki-en-documents.word"
ida = IDA(num_topics=20)
ida.initialization(train_input)
ida.sampling(10, 0.01, 0.01)

"""topic_0（京都について？）

kyoto: 858, station: 731, line: 652, emperor: 481, court: 446, period: 388, temple: 335, city: 318, imperial: 298, also: 253, end: 250, japan: 247, prince: 235, day: 227, area: 211, prefecture: 210, name: 205, rank: 205, family: 201, buddhism: 194, people: 183, old: 171, located: 171, section: 169, still: 167, university: 165, school: 160, japanese: 157, government: 157, history: 155,

topic_1（昔の京都？）

school: 310, kyoto: 308, temple: 251, station: 241, period: 224, line: 202, train: 179, system: 171, called: 166, imperial: 159, family: 156, served: 152, chief: 151, wooden: 146, railway: 142, clan: 132, special: 123, trains: 122, emperor: 121, given: 119, ministry: 119, subway: 119, daimyo: 114, one: 112, political: 112, fujiwara: 110, left: 105, times: 104, 1: 104, city: 102, 

topic_2（昔の京都の天皇？）

emperor: 678, kyoto: 564, city: 525, time: 456, period: 447, temple: 362, station: 349, family: 313, prefecture: 294, school: 285, called: 276, line: 270, three: 264, name: 247, japan: 229, also: 228, train: 224, shogun: 216, military: 212, service: 209, would: 206, keihan: 206, made: 205, imperial: 202, fujiwara: 195, considered: 193, first: 191, part: 186, restoration: 186, within: 186, 

topic_3（将軍とかあるから昔の京都？）

line: 265, station: 200, clan: 192, city: 179, shogunate: 173, many: 170, new: 168, kyoto: 157, lord: 155, head: 151, school: 140, used: 136, since: 127, temple: 122, well: 122, ward: 113, name: 112, war: 106, first: 105, faculty: 104, time: 103, although: 103, two: 101, said: 100, established: 100, railway: 98, education: 95, track: 92, uji: 91, mountain: 90, 

topic_4（）

station: 281, street: 226, line: 179, first: 157, time: 133, world: 132, since: 129, party: 119, records: 99, kyoto: 98, many: 93, relationship: 91, role: 90, ayabe: 90, said: 89, passed: 88, statues: 87, prefecture: 86, place: 85, education: 85, became: 85, period: 82, work: 79, japan: 79, empress: 79, era: 78, fukuchiyama: 78, teacher: 77, horikawa: 74, lord: 73, 

topic_5

emperor: 1065, also: 521, temple: 510, trains: 400, kyoto: 383, city: 359, high: 351, based: 349, mt: 333, group: 301, known: 298, one: 293, nara: 285, west: 278, line: 269, express: 268, literature: 261, castle: 257, style: 249, order: 244, cultural: 237, branch: 235, main: 223, mother: 220, training: 218, period: 215, control: 215, science: 214, april: 212, god: 209, 

topic_6

family: 483, station: 454, imperial: 365, prefecture: 318, temple: 297, kyoto: 286, line: 260, city: 253, university: 253, railway: 251, side: 236, also: 234, name: 208, however: 203, operated: 202, national: 190, period: 178, tokyo: 174, one: 168, although: 168, southern: 166, became: 165, street: 163, osaka: 162, section: 161, written: 160, people: 160, castle: 157, style: 154, ryoma: 154, 

topic_7

subway: 128, station: 65, religious: 63, issued: 58, affairs: 58, operating: 57, 2: 53, building: 53, generation: 52, attack: 50, field: 48, wind: 46, one: 46, shinto: 43, started: 43, kyoto: 42, furthermore: 42, school: 42, train: 42, living: 41, including: 40, master: 39, okubo: 38, disciple: 37, roof: 37, located: 37, white: 36, back: 36, nagahama: 36, period: 35, 

topic_8

kyoto: 334, station: 269, clan: 162, period: 102, shogun: 90, first: 88, 1: 88, family: 86, shrine: 83, time: 82, also: 82, 4: 77, front: 74, japan: 74, said: 71, temple: 71, minister: 70, current: 69, koku: 68, largest: 67, school: 67, kyushu: 66, local: 66, early: 64, established: 64, keihan: 63, festival: 62, could: 62, due: 62, jr: 62, 

topic_9

station: 438, kyoto: 322, temple: 256, among: 239, province: 198, city: 171, called: 167, emperor: 162, shrine: 157, imperial: 153, also: 145, retired: 141, school: 135, main: 121, two: 117, osaka: 117, later: 114, october: 112, railway: 110, clan: 109, japanese: 109, november: 106, street: 105, area: 104, hankyu: 98, line: 97, family: 95, first: 94, territory: 93, former: 91, 

topic_10

school: 136, station: 127, university: 112, fujiwara: 92, position: 88, kyoto: 88, meiji: 87, later: 79, chief: 76, latter: 74, shrine: 72, following: 71, death: 69, development: 68, clan: 64, various: 63, court: 62, streets: 62, however: 60, support: 59, already: 59, 1: 59, korea: 55, arts: 54, 10: 52, three: 52, 8: 51, express: 49, called: 47, faith: 47, 

topic_11

school: 223, kyoto: 222, japanese: 202, imperial: 180, station: 162, court: 154, time: 136, temple: 134, emperor: 129, three: 116, made: 106, line: 104, daughter: 103, used: 101, clan: 98, year: 90, name: 89, type: 89, considered: 86, city: 86, statue: 84, big: 84, 1: 84, etc: 83, also: 83, became: 82, office: 82, origin: 81, trains: 81, addition: 79, 

topic_12

station: 306, japan: 216, city: 199, established: 180, line: 179, kyoto: 176, temple: 171, school: 149, section: 144, building: 130, prefecture: 126, years: 125, three: 119, used: 117, period: 111, war: 110, imperial: 110, clan: 105, son: 104, first: 102, domain: 102, made: 99, series: 93, time: 93, area: 89, died: 88, times: 87, described: 87, shogun: 86, km: 83, 

topic_13

line: 194, station: 194, temple: 145, kyoto: 111, railway: 94, section: 77, imperial: 77, name: 70, train: 70, japan: 69, city: 66, center: 61, family: 60, later: 57, may: 56, period: 55, changed: 53, province: 53, among: 51, research: 51, school: 50, daughter: 48, osaka: 47, used: 45, emperor: 43, also: 43, would: 42, division: 42, located: 41, well: 38, 

topic_14

station: 708, kyoto: 548, temple: 354, also: 276, family: 225, section: 220, university: 219, shrine: 217, line: 215, government: 206, emperor: 194, however: 193, one: 185, period: 172, called: 165, became: 160, city: 156, trains: 155, opened: 154, people: 149, school: 145, faculty: 145, japanese: 140, court: 138, main: 134, later: 128, local: 123, chief: 114, imperial: 112, established: 111, 

topic_15

station: 347, line: 212, two: 201, march: 197, kyoto: 171, shrine: 165, emperor: 146, made: 143, days: 140, temple: 138, bridge: 136, area: 134, work: 134, son: 132, ancient: 129, throne: 122, presentday: 119, words: 114, japan: 114, osaka: 112, city: 110, post: 109, capital: 108, august: 104, literally: 103, number: 95, southern: 95, bus: 93, text: 92, tried: 92, 

topic_16

kyoto: 718, city: 534, imperial: 487, school: 416, one: 380, became: 377, station: 366, period: 336, system: 312, prefecture: 299, temple: 292, national: 278, also: 273, shrine: 271, prince: 262, called: 256, cultural: 254, province: 251, clan: 250, great: 243, family: 238, line: 216, four: 210, stations: 205, person: 203, old: 195, tokugawa: 191, years: 183, two: 176, university: 168, 

topic_17（）

urban: 86, attached: 79, river: 60, used: 56, series: 56, travel: 55, line: 55, politics: 52, living: 52, defeated: 51, japan: 48, location: 46, today: 45, court: 45, addition: 44, station: 43, space: 41, priest: 40, secular: 37, rule: 35, school: 34, put: 34, left: 34, language: 34, jr: 34, chief: 33, inside: 33, clan: 32, exist: 32, special: 32, 

topic_18（なんか暴動とか事件ぽい？）

grade: 73, list: 61, station: 55, memorial: 51, hall: 49, vocational: 48, center: 47, commander: 47, transferred: 46, coast: 43, shrine: 42, officer: 42, serious: 41, japan: 40, inari: 40, section: 38, line: 38, force: 37, guest: 37, making: 37, 1923: 36, captured: 36, thereby: 35, railway: 34, chemistry: 34, lineage: 32, ward: 32, troops: 32, strong: 31, brought: 31, 

topic_19（神社について？）

temple: 150, called: 140, station: 138, emperor: 126, school: 125, west: 116, one: 113, university: 113, gate: 112, kyoto: 111, order: 107, even: 87, middle: 81, city: 77, region: 76, national: 73, due: 73, northern: 68, april: 67, municipal: 65, nara: 64, many: 63, 1: 61, onmyoji: 61, number: 60, name: 58, outside: 58, period: 57, followed: 57, regular: 57, 
"""